import React from "react";
import StudentTable from "./components/StudentTable";

const StudentPage = () => {
  const fakeStudents = [
    {
      id: 1,
      user_id: 101,
      student_code: "ST001",
      full_name: "John Doe",
      gender: "male",
      birth_date: "2000-01-15",
      phone: "0123456789",
      address: "123 Main Street",
      province: "Province A",
      district: "District 1",
      ward: "Ward X",
      department: "Computer Science",
      major: "Software Engineering",
      class_name: "SE2023A",
      school_year: 2023,
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789012",
      emergency_contact_name: "Jane Doe",
      emergency_contact_phone: "0987654321",
      emergency_contact_relationship: "Parent",
      status: "active",
    },
    {
      id: 2,
      user_id: 102,
      student_code: "ST002",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
      status: "active",
    },
    {
      id: 3,
      user_id: 103,
      student_code: "ST003",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
      status: "active",
    },
    {
      id: 4,
      user_id: 104,
      student_code: "ST004",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 5,
      user_id: 105,
      student_code: "ST005",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 6,
      user_id: 106,
      student_code: "ST006",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 7,
      user_id: 107,
      student_code: "ST007",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 8,
      user_id: 108,
      student_code: "ST008",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 9,
      user_id: 109,
      student_code: "ST009",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 10,
      user_id: 110,
      student_code: "ST010",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 11,
      user_id: 111,
      student_code: "ST011",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 12,
      user_id: 112,
      student_code: "ST012",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 13,
      user_id: 113,
      student_code: "ST013",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 14,
      user_id: 114,
      student_code: "ST014",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
    {
      id: 15,
      user_id: 115,
      student_code: "ST015",
      full_name: "Alice Smith",
      gender: "female",
      birth_date: "2001-03-20",
      phone: "0123456788",
      address: "456 Oak Avenue",
      province: "Province B",
      district: "District 2",
      ward: "Ward Y",
      department: "Computer Science",
      major: "Data Science",
      class_name: "DS2023A",
      school_year: 2023,
      status: "active",
      avatar_path: "/avatars/default.png",
      citizen_id: "123456789013",
      emergency_contact_name: "Bob Smith",
      emergency_contact_phone: "0987654322",
      emergency_contact_relationship: "Parent",
    },
  ];

  return (
    <div>
      <StudentTable data={fakeStudents} />
    </div>
  );
};

export default StudentPage;
